version: '2.0'
services:
  jenkins:
    image: 'jenkins/jenkins:2.431-jdk17'
    volumes:
      - './jenkins-data:/var/jenkins_home'
    container_name: jenkins
    hostname: jenkins
    ports:
      - '81:8080'
      - '50000:50000'